version: 2
updates:
  - package-ecosystem: github-actions
    directory: .github/workflows
    schedule:
      interval: monthly

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    groups:
      - package-ecosystem: 'npm'
        group-name: 'all-npm-updates'
        packages:
          - match:
              dependency_type: 'all'
